name: gurlingo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1 # Added the correct, null-safe audio package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # This section is crucial for your quiz sounds to work!
  assets:
    - assets/audio/
    - assets/images/